# Generated by Django 6.0.2 on 2026-04-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', '-created_at'],
                'indexes': [models.Index(fields=['user', 'label'], name='tags_tag_user_id_1f1297_idx'), models.Index(fields=['content_type', 'object_id'], name='tags_tag_content_9aa2bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'label'), name='unique_tag_per_item_for_user')],
            },
        ),
    ]
