# Generated by Django 6.0.2 on 2026-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
