# Generated by Django 6.0.2 on 2026-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceitem',
            options={'ordering': ['sort_order', 'created_at', 'name']},
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
